<?xml version='1.0'?><!DOCTYPE TEI.2 PUBLIC '-//TEI P4//DTD Main Document Type//EN' 'http://www.tei-c.org/Guidelines/DTD/tei2.dtd' [<!ENTITY % TEI.prose 'INCLUDE'><!ENTITY % TEI.linking 'INCLUDE'><!ENTITY % TEI.figures 'INCLUDE'><!ENTITY % TEI.analysis 'INCLUDE'><!ENTITY % TEI.corpus 'INCLUDE'><!ENTITY % TEI.XML 'INCLUDE'><!NOTATION TEI-XML PUBLIC 'TEI P4' 'http://www.tei-c.org/Guidelines/DTD/tei2.dtd'><!-- internal INL dtd --><!ELEMENT b (#PCDATA)><!ELEMENT l (#PCDATA | b)*><!-- end of internal INL dtd -->]><TEI.2><!--<ENTRY id="i598"><teiHeader><fileDesc><titleStmt><title>Onge&iuml;dentificeerd (1)</title>
</titleStmt>
<interpGrp type="pubYear_from"><interp value="1200"/></interpGrp>
<interpGrp type="witnessYear_from"><interp value="1200"/></interpGrp>
<interpGrp type="pubYear_to"><interp value="1250"/></interpGrp>
<interpGrp type="witnessYear_to"><interp value="1250"/></interpGrp>
<TITEL>Onge&iuml;dentificeerd (1)</TITEL>
<author>Onbekend</author>
<AARD>Rijm</AARD>
<BRON nr="K92">Krak&oacute;w, Biblioteka Jagiellonska, olim: Berlijn, Preussische Staatsbibliothek, Germ. qu. 1303,1 (fragm.)</BRON>
<DATUM>1200-1250</DATUM>
<OMVANG>147 verzen</OMVANG>
<BRON.OPM>Een dubbelblad, waarvan het voorste blad zodanig is afgesneden, dat alleen het begin (een enkel woord en wat letters) van iedere regel op de rectozijde bewaard is gebleven (restanten van in totaal 29 verzen). Per bladzijde &eacute;&eacute;n kolom van 29-30 regels. Per regel een rijmpaar, waarbij de verzen door een punt gescheiden zijn. De tekst van fol. 2 omvat 118 verzen, die tot het einde van het gedicht behoren. Beschreven wordt de terugkeer van Henric van Normandye naar Frankrijk, na zeven jaar strijd tussen christenen en heidenen. Hij heeft Claredamye, de dochter van de heidense koning van Mekka, verworven en tot het christendom bekeerd. Bij hen voegt zich Melantwier, een neef van Henric, en diens 'amye'. De tocht gaat van Jeruzalem over zee naar Normandi&euml;.</BRON.OPM>
<EDITIE>G. de Smet: 'Ein vergessenes Bruchst&uuml;ck eines mittelniederl&auml;ndischen Romans aus dem 13. Jahrhundert'. In: Studia Germanica Gandensia 11 (1969), 173-199 (176-179).</EDITIE>
<STATUS>Kritisch</STATUS>
<EDITIE.OPM>De editie is naar de editie Bartsch uit 1860, omdat het fragment zelf destijds zoek was (zie K. Bartsch: 'Bruchst&uuml;cke eines niederrheinischen epischen Gedichtes'. In: Germania 5 (1860), 356-361).  In het fragment bestaat iedere regel uit een rijmpaar, waarbij de verzen door een punt zijn gescheiden. In de editie worden de beide leden van deze rijmparen als twee afzonderlijke regels weergegeven, waardoor ze twee keer zoveel regels telt als het fragment. In de editie is fol. 1 "Blatt II" en fol. 2 "Blatt I" (hoewel de editeur weet dat het tweede blad aan het eerste voorafging). Anders dan in de editie, waarin de regels van het eerste en het tweede blad afzonderlijk zijn genummerd, is hier gekozen voor een doorlopende regelnummering. Verder is hier bij fol. 1 aan het eind van iedere regel aangegeven dat er een gedeelte is verdwenen, terwijl dit in de editie meestal niet is gedaan. In het kritisch apparaat van de editie komen de volgende aantekeningen voor: regel 64: lees "bl&icirc;tschaf"; regel 125: misschien "talemye"; regel 140: misschien "ged&icirc;en".</EDITIE.OPM>
<BRONNEN>Krak&oacute;w, Biblioteka Jagiellonska, olim: Berlijn, Preussische Staatsbibliothek, Germ. qu. 1303,1 (fragm.)</BRONNEN>
</fileDesc>
</teiHeader>
--><text>
<l parse="ignore"><pb n="179"/><milestone unit="fol" n="1r"/> ne quame [...]</l>
<l parse="ignore">sie die d[...]</l>
<l parse="ignore">sprach de be[...]</l>
<l parse="ignore">te mi gehabe [...]</l>
<l parse="ignore" n="5">sal ic biden [...]</l>
<l parse="ignore">die hie[...]</l>
<l parse="ignore">vmbe mic [...]</l>
<l parse="ignore">Muder en[...]</l>
<l parse="ignore">[enlie(?) ende(?) ...]</l>
<l parse="ignore" n="10">ore heidhen [...]</l>
<l parse="ignore">baz dan diek[irsten(?) ...]</l>
<l parse="ignore">van den [...]</l>
<l parse="ignore">ende fure[...]</l>
<l parse="ignore">Got d[...]</l>
<l parse="ignore" n="15">De konenc [...]</l>
<l parse="ignore">dat sal mot[...]</l>
<l parse="ignore">dat se seker [...]</l>
<l parse="ignore">ent[.] ie[..g..]</l>
<l parse="ignore">[...]</l>
<l parse="ignore" n="20">en[...] se[...]</l>
<l parse="ignore">dat nit wal [...]</l>
<l parse="ignore">dat ic nv [...]</l>
<l parse="ignore">ent ic vu[...]</l>
<l parse="ignore">do sprach [...]</l>
<l parse="ignore" n="25">Mire [...]</l>
<l parse="ignore">der wi vor [...]</l>
<l parse="ignore">dat uvele [...]</l>
<l parse="ignore">[...]e dohter [...]</l>
<l parse="ignore">sprach herre [...]</l>
<l n="30"><pb n="176"/><milestone unit="fol" n="2r"/> met or ec vmbe dusent pvnt.</l>
<l>si wolde si als einen hunt</l>
<l>hazen miden ende ueidhen,</l>
<l>sine liete uan den heidhen</l>
<l>ent gerne zu nsen gode</l>
<l n="35">kerde, de alle dinc te sinen gebode</l>
<l>staen ent sire gewolt.</l>
<l>der heidhen gode waren golt</l>
<l>siluer ent gesteine,</l>
<l>doit al gemeine,</l>
<l n="40">beidhe blint ende dof.</l>
<l>sine mohten met dan ein lof</l>
<l>helpe uerlien.</l>
<l>hine kunde uerdien</l>
<l>di em dinest dade,</l>
<l n="45">ofte si genade bade.</l>
<l>si emboit or dat si sage</l>
<l>wie dat maumet lage</l>
<l>van oren amise te slagen,</l>
<l>ent he dat mvste uerdragen</l>
<l n="50">dorg noit dat he die steine nam</l>
<l>ende waldelike mide quam</l>
<l>dar si selue wolde.</l>
<l>si enboit dat si solde</l>
<l>entsegen den uerwaten</l>
<l n="55">ent sich kirsten laten.</l>
<l>si wolde dan openbare,</l>
<l>so war or leef ware,</l>
<l>na or te sprekene komen.</l>
<l>do dat or mvder uernomen</l>
<l n="60">hatte dat si or enboit,</l>
<l>do was or iamer harde groit.</l>
<l>si sprac an svaren herte</l>
<l>`woch arme, dirre smerte!</l>
<l>nv is min blithaf als ein wint,</l>
<l n="65">nv min eneget kint</l>
<l>mine ruket te siene.</l>
<l>hir entsegic al gemeine</l>
<l>minen goden ueruluken.</l>
<l><edition n="177"/>jc biden mi te suken</l>
<l n="70">sulken, de mi nake gode'.</l>
<l>do was schire enwech de bode,</l>
<l>de dit der dohter dede uerstaen.</l>
<l>do wart kirsten gedaen</l>
<l>van mec die koninginne,</l>
<l n="75">ent wart met guder minne</l>
<l>entfaen uan claredamye.</l>
<l>si gaf do den uan normandye</l>
<l>tve dusent marc uan golde</l>
<l>t dien dat he holde</l>
<l n="80">minne t ore dohter druge.</l>
<l>dat na kerde si met geuuge</l>
<l>widhe tu ores selues lande</l>
<l>met groter ere sunder schande.</l>
<l>Got, de mi ter werelde sande,</l>
<l n="85">de behude mi an rehte stande.</l>
<l>Do die urowe widher quam</l>
<l>ent de konenc uernam,</l>
<l>dat si or gescheidhen</l>
<l>hatte uan den heidhen,</l>
<l n="90"><milestone unit="fol" n="2v"/> des was he tornich sere</l>
<l>des he siner ere</l>
<l>lucel gedahte.</l>
<l>he liet harde vnsahte</l>
<l>die koninginne doden.</l>
<l n="95">si wart uan allen noden</l>
<l>ledheget an der sele</l>
<l>met gerehten [iubele(?)].</l>
<l>ent he was verwaten.</l>
<l>dat sal ic also laten</l>
<l n="100">ende segen uort di mare.</l>
<l>do wart geueidhet seuen iare</l>
<l>tuschen kirsten ende heidhen,</l>
<l>do wolde henric danne scheidher</l>
<l>ent urou claredamye.</l>
<l n="105">melantwier ent sine amye</l>
<l>wolden oc met en te lande.</l>
<l>henric oc te schippe sande</l>
<l>beidhe siluer ende golt</l>
<l><edition n="178"/>ende cryode maneuolt</l>
<l n="110">doch gauen si den kirsten,</l>
<l>da se die armen wisten,</l>
<l>met groten eren or gut.</l>
<l>do wat was an oren mut</l>
<l>dat si selue wolden uaren,</l>
<l n="115">do beualen si an godes waren</l>
<l parse="ignore">den riken konenc a[m/d(?)]erade.</l>
<l parse="ignore">[...] en gestaen an sinen rade</l>
<l>si waren bliven alle.</l>
<l>sit gaf he met geualle</l>
<l n="120">vrlof den heren</l>
<l>ende se begunden keren</l>
<l>van ierusalem an der stunt</l>
<l>ende quamen w[a/o(?)]l gesunt</l>
<l>widher te normandye,</l>
<l n="125">jt ware eine tale nye</l>
<l>ent alte lanc vch te reken,</l>
<l>soldic uan des landes recken</l>
<l>segen wie si entfiengen,</l>
<l>met wilken eren si begingen</l>
<l n="130">die heren ent or kompanye.</l>
<l>do was ledhic normandye</l>
<l>van den konenge uan urancrike.</l>
<l>des mohte dar gewaldenlike</l>
<l>henric dun dat on gut duhte.</l>
<l n="135">nit wal ic gesegen mohte</l>
<l>van aldes landes urowen,</l>
<l>wie si met gerehten trowen</l>
<l>entfiengen claredamyen</l>
<l>ent melantwieres amyen.</l>
<l n="140">Got late mi noc so gien</l>
<l>ende dit ende nit uertien.</l>
<l>Henric do boden sande</l>
<l>v[u]rwart in alle v lande,</l>
<l>einen turney uermeren</l>
<l n="145">den schonen urowen te eren,</l>
<l>der konengen Claredamyen</l>
<l>ende sines neuen amyen.</l>
</text>
<!--</ENTRY>
--></TEI.2>
